n= input('Digite alguma coisa = ')
print ('O tipo primitivo desse valor é', type (n))
print ('É composto apenas por espaços?', n.isspace())
print ('É uma letra do alfabeto?', n.isalpha())
print ('É um número?', n.isnumeric())
print ('É uma letra do alfabeto ou número?', n.isalnum())
print ('Está em caixa alta?', n.isupper())
print ('Está em caixa baixa?', n.islower())
print ('Está capitalizada?', n.istitle())
