nome = str(input('Digite seu nome completo: ')).strip()
print('Seu nome em letras minúsculas é: {}.'.format(nome.lower()))
print('Seu nome em letras maiúsculas é: {}.'.format(nome.upper()))
print('Seu nome completo tem {} letras.'.format(len(nome) - nome.count(' ')))
nseparado = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras.'.format(nseparado[0], len(nseparado[0])))
